name: Website

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - staging
jobs:
  pages:
    runs-on: ubuntu-latest
    if: github.repository == 'gfilicetti/gHacks'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set branch specific variables
      id: environment
      run: |
        if [[ "${GITHUB_REF#refs/heads/}" =~ (main|staging) ]]; then
          echo "BRANCH_SPECIFIC_BUCKET_NAME=GCS_BUCKET_${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        else
          echo "BRANCH_SPECIFIC_BUCKET_NAME=GCS_BUCKET_staging" >> $GITHUB_OUTPUT
        fi
    - name: Split the files 
      run: |
        tools/setup-pages.sh
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'    
    - name: Build Jekyll Pages
      run: |
        NOKOGIRI_USE_SYSTEM_LIBRARIES=true bundle install --quiet --gemfile=tools/Gemfile
        github-pages build --source=dist
    - name: GCP Login
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - name: Publish to GCS
      run: gsutil -m -q rsync -d -r _site ${{ secrets[steps.environment.outputs.BRANCH_SPECIFIC_BUCKET_NAME] }}
