name: Validation

on: 
  pull_request:
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Split the files 
      run: |
        tools/setup-pages.sh
